# whether or not users need to be approved to upload.
user_approval = false

# Version of the site shown on the changelog.
version = "0.0"

# flask secret key.
flask_secret_key = ""
# url to database
database_url = ""

# upload limit for files (measured in megabytes)
mb_upload_limit = 10
# the number of samples to show per each page of samples.
samples_per_page = 25
# file extensions allowed for upload
allowed_upload_extensions = ["mp4"]

# email login, for verification
mail_server=""
mail_port=587
mail_use_tls = true  # Use TLS for most SMTP providers
mail_use_ssl = false # Use SSL only if required (never enable both)
mail_username=""
mail_password=""

