"""add missing columns

Revision ID: 209c865d72be
Revises: 34fb43d59f3d
Create Date: 2026-09-29 20:33:19.078737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '209c865d72be'
down_revision = '34fb43d59f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.drop_column('tags')
    op.execute('UPDATE sample SET is_public = true WHERE is_public IS NULL')
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('is_public', nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET join_date = now() WHERE join_date IS NULL')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('join_date', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('join_date')

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
